import { Outfit } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import Header from "./_components/Header";
// import NextAuthSessionProvider from "./provider";
// import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./provider";
const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Haven Assist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

          <Header/>
          
              <div className=" mx-6 md:mx-16">
                  {children}
              </div>
        </Providers>

        </body>
    </html>
  );
}
